spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-bp1iml36y247329g2lo.mysql.rds.aliyuncs.com:3306/sprider?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: sprider2
      password: o0w6d^8GJEbU^XZF4um*UvsF$yJ9Zw
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: docker-cluster
      cluster-nodes: 172.16.30.177:9300
  elasticsearch:
    rest:
      uris: 172.16.30.177:9200

  #redis
  redis:
    database: 0
    host: 172.16.30.177
    port: 6379
    password: j6ixcv2airw
    timeout: 8000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 20  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8     # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接


  #rabbitmq
  rabbitmq:
    host: 172.16.30.177
    port: 5672
    username: jin10
    password: j6ixcv2airw
    publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回调
    virtual-host: /

#用户自定义参数
custom:
  nativeAddress: http://172.16.30.177:7100/
  serverAddress: http://172.16.30.177:7200/
  dingding:
    receiver: 18883179959,13726218258,18814374928
    adminUrl: https://oapi.dingtalk.com/robot/send?access_token=8d25a92f4738258270d496dc4940d5d43004f1117e719dd7190c3d75d73ead0c #调度警告
    httpDispatchUrl: https://oapi.dingtalk.com/robot/send?access_token=aeca03649b5f2ef6e0389cb8d86b3bb16ac8b2e6cdd3e9e102745ae492c4e9d4
    secretKeyUrl: https://oapi.dingtalk.com/robot/send?access_token=4956562a25641fc41c852564a035bdd30aacf3268da00e64c7255f33f7cfe322
    secretKey: SECb9ab381bffacd2198af185c155ff0417836129f37e17b327384d7ab5787684ae
  spider:
    baseUrl: http://172.16.30.177:8880/ # 爬虫服务的url
    foreignUrl: http://47.88.10.134:8880/ # 国外服务器地址
  socket:
    serverUrl: ws://172.16.30.177:12550/ws
  ping:
    mainUrl: http://115.29.174.245/ping
    foreignUrl: http://47.88.10.134/ping



#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jin10.spider.spiderserver.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'


#logging:
#  config: classpath:logback.xml

xxl:
  job:
    admin:
      addresses: http://172.16.30.177:7300/xxl-job-admin
    executor:
      appname: spider-admin
      ip:
      port: 9995
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken:
