# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 100
    min-spare-threads: 50
    max-connections: 500
  port: 7100
  servlet:
    context-path: /admin

# dev prod
spring:
  profiles:
    active: dev # dev prod
  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  freemarker:
    suffix: .html
    request-context-attribute: request
  task:
    scheduling:
      thread-name-prefix: task-pool-
      pool:
        size: 10

