spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.232.136:3306/sprider?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  main:
    allow-bean-definition-overriding: true
  #redis
  redis:
    database: 7
    host: 192.168.232.136
    port: 6379
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接


  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: docker-cluster
      cluster-nodes: 192.168.232.136:9300
  elasticsearch:
    rest:
      uris: 192.168.232.136:9200

  shardingsphere:
    datasource:
      names: sprider
      sprider:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.232.136:3306/sprider?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    sharding:
      tables:
        spider_message:
          actual-data-nodes: sprider.spider_message_20$->{19..99}_${0..1}
          table-strategy:
            standard:
              sharding-column: time
              precise-algorithm-class-name: com.jin10.spider.spiderserver.service.impl.TimeShardingImpl





jwt:
  secret: mySecret
  header: Authorization
  expiration: 604800
  tokenHead: Bearer



#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jin10.spider.spiderserver.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

custom:
  admin:
    url: http://localhost:7100 # http://192.168.60.129:7100
  push:
    url: http://localhost:14570
  dingding:
    receiver: 15986941493 # 18883179959,13726218258,18814374928
    httpUrl: https://oapi.dingtalk.com/robot/send?access_token=bd2012d22ea5ecb30e556d16ccacf46e98361af67573a48b3017c33dd8adc475
    httpDispatchUrl: https://oapi.dingtalk.com/robot/send?access_token=aeca03649b5f2ef6e0389cb8d86b3bb16ac8b2e6cdd3e9e102745ae492c4e9d4
  check: UGJJKoOj5e1